[tool.hatch.envs.default]
dependencies = [
  "copier",
  "uv"
]
scripts.copy = [
  "copier copy --vcs-ref=HEAD . {args:.tmp/aiida-test} -f",
]
scripts.install = [
  "copier copy --vcs-ref=HEAD . .tmp/aiida-test -f",
  "uv pip install .tmp/aiida-test",
]
scripts.check = [
  "copier copy --vcs-ref=HEAD . .tmp/aiida-test -f",
  "hatch fmt -l --check .tmp/aiida-test",
]
scripts.docs = [
  "copier copy --vcs-ref=HEAD . .tmp/aiida-test -f",
  "cd .tmp/aiida-test/docs && myst start",
]
scripts.clean = [
  "ruff clean",
  "rm -rf .tmp",
]


[tool.hatch.envs.docs]
detached = true
dependencies = [
  "mkdocs",
  "mkdocs-material"
]
scripts.build = "mkdocs build --clean --strict"
scripts.serve = "mkdocs serve --dev-addr localhost:8000"
scripts.deploy = "mkdocs gh-deploy --force"
