[tool.hatch.envs.docs]
dependencies = [
  "mkdocs",
  "mkdocs-material"
]
scripts.build = "mkdocs build --clean --strict"
scripts.serve = "mkdocs serve --dev-addr localhost:8000"
scripts.deploy = "mkdocs gh-deploy --force"


[tool.hatch.envs.template]
dependencies = [
  "copier",
  "uv"
]
scripts.copy = [
  "copier copy . .tmp -f -d plugin_name=aiida-test",
]
scripts.install = [
  "copier copy . .tmp -f -d plugin_name=aiida-test",
  "uv pip install .tmp/aiida-test",
]
scripts.check = [
  "copier copy . .tmp -f -d plugin_name=aiida-test",
  "hatch fmt -l --check .tmp/aiida-test",
]
scripts.clean = [
  "ruff clean",
  "rm -rf .tmp",
]