[tool.hatch.envs.template]
dependencies = [
  "copier",
  "uv"
]
scripts.install = [
  "copier copy . .tmp -f -d plugin_name=aiida-test",
  "uv pip install .tmp/aiida-test",
]
scripts.check = [
  "copier copy . .tmp -f -d plugin_name=aiida-test",
  "hatch fmt -l --check .tmp/aiida-test",
]
scripts.clean = [
  "ruff clean",
  "rm -rf .tmp",
]